Repository cloudera-labs/cdp-tf-quickstarts, pull requests merged in 2024-10, with the labels that each got.

#47 Pin to release 0.8.2 of modules
  .pre-commit-config.yaml
  LICENSE
  aws/main.tf
  aws/terraform.tfvars.template
  aws/variables.tf
  azure/main.tf
  azure/terraform.tfvars.template
  azure/variables.tf
  gcp/main.tf
  gcp/terraform.tfvars.template
  gcp/variables.tf
Labels: enhancement

#45 Readme Cloud Provider Notes
  README.md
Labels: enhancement

#51 Add subscription_id to azurerm and delegated_subnet inputs; update ingress note in readme
  README.md
  aws/terraform.tfvars.template
  azure/main.tf
  azure/terraform.tfvars.template
  azure/variables.tf
  gcp/terraform.tfvars.template
Labels: bug, documentation

#53 Pin to release 0.8.3 of modules
  aws/main.tf
  azure/main.tf
  gcp/main.tf
Labels: bug

#52 CB-27475 Cleaning up express onboarding outputs
  .github/workflows/push-quickstart-script-to-s3.yml
  aws/destroy.sh
  aws/quickstart.sh
  azure/destroy.sh
  azure/quickstart.sh
  gcp/destroy.sh
  gcp/quickstart.sh
Labels: enhancement
